### ISSUE TITLE
from-markdown to => 'pod6' fails to create first line '=begin pod' (the ending line is correct: '=end pod')

### ISSUE THREAD

**Issue by tbrowder** [antononcube/Raku-Markdown-Grammar#1]
Given a Markdown file 'test.md' with contents:

    line1

Run this code

    > use Markdown::Grammar;
    > my @pod = from-markdown "test.md';  
    =begin
    =para
    line1
    =end pod

Notice the incorrect first line: '=begin'  <== missing ' pod'

I have a work-around for now, but this seems like a serious bug.

**Comment by antononcube** [comment]
Thanks for reporting this! Should be fixed now. Please see: https://github.com/antononcube/Raku-Markdown-Grammar/commit/226f136f95a3fe6395d34056479d7c2c4a69ecd9 .

>I have a work-around for now, but this seems like a serious bug.

I agree. I have to make a comprehensive Pod6 test file. (My focus so far has been on Mathematica...)

Here is a start :) : https://github.com/antononcube/Raku-Markdown-Grammar/blob/main/t/04-Pod6.rakutest .

**Comment by antononcube** [comment]
Fixed.

**Comment by tbrowder** [comment]
Great, thanks! I just reported another.

But your module is my goto for md to pod now so I really appreciate your work!

**Comment by antononcube** [comment]
Thanks -- that is really motivational!
