### ISSUE TITLE
Markdown syntax for language in code clocks is not translated properly to Rakucoc

### ISSUE THREAD

**Issue by tbrowder** [antononcube/Raku-Markdown-Grammar#2]
Markdown

    ```raku

Rakupod

    =begin code :lang<raku>

This module 

    =begin code raku

**Comment by tbrowder** [comment]
I do have a workaround for now.

**Comment by antononcube** [comment]
Thanks for submitting that!

Should it be `:language<raku>` or `:lang<raku>`? 
In the documentation here : 

  https://docs.raku.org/language/pod#Configuration_information

I do not see a language key.

**Comment by antononcube** [comment]
Should be fixed (using the given suggestion in the report). See : https://github.com/antononcube/Raku-Markdown-Grammar/commit/7bf9dff7d63f3b829d17199233f4936bce70ff95

**Comment by antononcube** [comment]
Fixed. Added a corresponding test in : https://github.com/antononcube/Raku-Markdown-Grammar/blob/main/t/04-Pod6.rakutest .

**Comment by tbrowder** [comment]
I looked for a standard before I filed the issue, but didn't find one. But it's still proper format for a :config attribute. I should have looked in roast where the real specs are defined now.

**Comment by tbrowder** [comment]
Yes, look in roast dirs S01*/, S29*/, and S32*/.  Mostly :lang<Perl5> as an adverb. It's also used heavily in the doc sources.
