### ISSUE TITLE
In a code block, the :lang is not required, but if used it must not be empty

### ISSUE THREAD

**Issue by tbrowder** [antononcube/Raku-Markdown-Grammar#4]
If the original Markdown text has a code block without a language tag, then the corresponding Rakupod must not have an empty :lang option key, so do not include the key at all.

For example, given this Markdown

    ```
    {
        "name": "Anton"
    }
    ```

the resulting Rakupod should be

    =begin code
    {
        "name": "Anton"
    }
    =end code

An empty :lang option key is illegal, and the lack of a language config option key at all is not an error currently as far as I know.

The current version of `Markdown::Grammar` puts an empty :lang config option key given the Markdown code above. (Technically, you could put :lang without the empty angle brackets and it should parse okay, but I don't think I would do that without consensus from core devs.)

**Comment by antononcube** [comment]
I noticed and fixed this yesterday (while preparing the "Conversion and evaluation of Raku files" presentation).
See the fix at "lib/Markdown/Actions/Pod6.rakumod" in here: https://github.com/antononcube/Raku-Markdown-Grammar/commit/7cf2db88ee30c499034668ab9212bafcbde88248 .

I just uploaded my latest repository version, 4.0, to [raku.land](https://raku.land/zef:antononcube/Markdown::Grammar).

**Comment by antononcube** [comment]
I added test in https://github.com/antononcube/Raku-Markdown-Grammar/blob/main/t/04-Pod6.rakutest .
