### ISSUE TITLE
Undefined variable warnings when generating pod6

### ISSUE THREAD

**Issue by 2colours** [antononcube/Raku-Markdown-Grammar#5]
[warnings.txt](https://github.com/antononcube/Raku-Markdown-Grammar/files/10552811/warnings.txt)

[README.md](https://github.com/antononcube/Raku-Markdown-Grammar/files/10552813/README.md)

When executing `from-markdown README.md --to=pod6` with the given file, I get the given error, using:
- Rakudo 2022.12 with MoarVM
- WSL2, with Ubuntu 20.04 inside

Could you please take a look at what causes the warnings and if they have troublesome side effects?
Thank you.

**Comment by antononcube** [comment]
Thank you for reporting this issue!

Should be fixed with https://github.com/antononcube/Raku-Markdown-Grammar/commit/739c403c4de4d4abce26e887092af72694a5b3fa .

(I have not uploaded the fixed version of the package to raku.land yet. The new version number would be: 0.4.4+.)
